version: '3.8'
services:
  sora-nginx:
    container_name: sora-nginx
    build:
      context: ./
      dockerfile: dockerfile.nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      #todo:
      - ./www:/var/www/html
#      - ./storage:/home/ledums/storage/:delegated
#      - ./php_conf/profiler:/tmp/profiler:delegated
#      - ./logs/nginx:/var/log/nginx:delegated
#      - ./nginx_conf:/etc/nginx/conf.d:cached
    networks:
      - sora-network

  sora-fpm:
    container_name: sora-fpm
    build:
      context: ./
      dockerfile: dockerfile.fpm
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./www:/var/www/html/:rw
#      - ./storage:/home/ledums/storage/
#      - ./php_conf/profiler:/tmp/profiler:delegated
#      - ./logs/php-fpm:/var/log:delegated
#      - ./php_conf/php.ini:/usr/local/etc/php/php.ini:cached
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      FORCE_SSL: "false"
      XDEBUG_CONFIG: "client_host=172.17.0.1"
      APP_ENV: dev # environment
      #XDEBUG_CONFIG: "remote_host=host.docker.sora-network remote_enable=1"
      #APP_ENV: ${APP_ENV}
    networks:
      - sora-network

  sora-mysql:
    container_name: sora-mysql
    platform: linux/x86_64
    image: mysql:5.7.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sora
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
    restart: always
    networks:
      - sora-network

  sora-redis:
    container_name: sora-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - sora-network

  sora-nodejs:
    container_name: sora-nodejs
    build:
      context: .
      dockerfile: dockerfile.nodejs
    restart: always
    volumes:
      - ./www:/var/www/html:cached
      - ./public:/var/www/html/public:rw,delegated
    environment:
      WEB_HOST: ${WEB_HOST}
      WEB_PORT: 80
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - sora-network

  sora-apollo:
    container_name: sora-apollo
    image: sora-nodejs
    working_dir: /apollo
    volumes:
      - ./apollo:/apollo
    ports:
      - "4000:4000"
    command: [ "npm", "start" ]
    networks:
      - sora-network

  sora-opensearch:
    container_name: sora-opensearch
    image: opensearchproject/opensearch:2.3.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISCOVERY_TYPE: single-node
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin
    ports:
      - "9200:9200"
    networks:
      - sora-network

networks:
  sora-network:
    driver: bridge