FROM node:22.7.0-alpine3.20

WORKDIR /var/www

RUN touch /usr/local/bin/nodejs.sh
COPY /docker/nodejs/nodejs.sh /usr/local/bin/nodejs.sh
RUN chmod 777 /usr/local/bin/nodejs.sh

CMD ["sh", "/usr/local/bin/nodejs.sh"]