#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- node "$@"
fi

if [ "$1" = 'node' ] || [ "$1" = 'yarn' ]; then
    yarn config set "strict-ssl" false -g
	yarn install

	>&2 echo "Waiting for WEB to be ready..."
	until nc -z "$WEB_HOST" "$WEB_PORT"; do
		sleep 1
	done
fi

exec "$@"
